// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package smart.air.pollution.airquality;

public final class AirQualityServiceImpl {
  private AirQualityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLatestAirQualityDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetLatestAirQualityDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetLatestAirQualityDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetLatestAirQualityDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAirQualityDataByTimeRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAirQualityDataByTimeRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAirQualityDataByTimeRangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAirQualityDataByTimeRangeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pollutant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pollutant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AirQualityService.proto\"2\n\036GetLatestAi" +
      "rQualityDataRequest\022\020\n\010location\030\001 \001(\t\"f\n" +
      "\037GetLatestAirQualityDataResponse\022\013\n\003aqi\030" +
      "\001 \001(\005\022\036\n\npollutants\030\002 \001(\0132\n.Pollutant\022\026\n" +
      "\016health_effects\030\003 \001(\t\"]\n#GetAirQualityDa" +
      "taByTimeRangeRequest\022\020\n\010location\030\001 \001(\t\022\022" +
      "\n\nstart_time\030\002 \001(\003\022\020\n\010end_time\030\003 \001(\003\"f\n$" +
      "GetAirQualityDataByTimeRangeResponse\022\021\n\t" +
      "TimeStamp\030\001 \001(\003\022\013\n\003aqi\030\002 \001(\005\022\036\n\npollutan" +
      "ts\030\003 \001(\0132\n.Pollutant\"(\n\tPollutant\022\014\n\004nam" +
      "e\030\001 \001(\t\022\r\n\005level\030\002 \001(\0022\344\001\n\021AirQualitySer" +
      "vice\022^\n\027GetLatestAirQualityData\022\037.GetLat" +
      "estAirQualityDataRequest\032 .GetLatestAirQ" +
      "ualityDataResponse\"\000\022o\n\034GetAirQualityDat" +
      "aByTimeRange\022$.GetAirQualityDataByTimeRa" +
      "ngeRequest\032%.GetAirQualityDataByTimeRang" +
      "eResponse\"\0000\001B9\n\036smart.air.pollution.air" +
      "qualityB\025AirQualityServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetLatestAirQualityDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetLatestAirQualityDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetLatestAirQualityDataRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_GetLatestAirQualityDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetLatestAirQualityDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetLatestAirQualityDataResponse_descriptor,
        new java.lang.String[] { "Aqi", "Pollutants", "HealthEffects", });
    internal_static_GetAirQualityDataByTimeRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetAirQualityDataByTimeRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAirQualityDataByTimeRangeRequest_descriptor,
        new java.lang.String[] { "Location", "StartTime", "EndTime", });
    internal_static_GetAirQualityDataByTimeRangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAirQualityDataByTimeRangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAirQualityDataByTimeRangeResponse_descriptor,
        new java.lang.String[] { "TimeStamp", "Aqi", "Pollutants", });
    internal_static_Pollutant_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Pollutant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pollutant_descriptor,
        new java.lang.String[] { "Name", "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
