// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AirQualityService.proto

package smart.air.pollution.airquality;

public interface GetLatestAirQualityDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetLatestAirQualityDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 aqi = 1;</code>
   */
  int getAqi();

  /**
   * <code>.Pollutant pollutants = 2;</code>
   */
  boolean hasPollutants();
  /**
   * <code>.Pollutant pollutants = 2;</code>
   */
  smart.air.pollution.airquality.Pollutant getPollutants();
  /**
   * <code>.Pollutant pollutants = 2;</code>
   */
  smart.air.pollution.airquality.PollutantOrBuilder getPollutantsOrBuilder();

  /**
   * <code>string health_effects = 3;</code>
   */
  java.lang.String getHealthEffects();
  /**
   * <code>string health_effects = 3;</code>
   */
  com.google.protobuf.ByteString
      getHealthEffectsBytes();
}
