// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlertService.proto

package smart.air.pollution.alert;

public final class AlertServiceImpl {
  private AlertServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscribeToPollutantAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscribeToPollutantAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnsubscribeFromAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnsubscribeFromAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pollutant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pollutant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AlertService.proto\032\033google/protobuf/em" +
      "pty.proto\"U\n!SubscribeToPollutantAlertsR" +
      "equest\022\020\n\010location\030\001 \001(\t\022\036\n\npollutants\030\002" +
      " \003(\0132\n.Pollutant\"0\n\034UnsubscribeFromAlert" +
      "sRequest\022\020\n\010location\030\001 \001(\t\"(\n\tPollutant\022" +
      "\014\n\004name\030\001 \001(\t\022\r\n\005level\030\002 \001(\0022\276\001\n\014AlertSe" +
      "rvice\022\\\n\032SubscribeToPollutantAlerts\022\".Su" +
      "bscribeToPollutantAlertsRequest\032\026.google" +
      ".protobuf.Empty\"\000(\001\022P\n\025UnsubscribeFromAl" +
      "erts\022\035.UnsubscribeFromAlertsRequest\032\026.go" +
      "ogle.protobuf.Empty\"\000B/\n\031smart.air.pollu" +
      "tion.alertB\020AlertServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_SubscribeToPollutantAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubscribeToPollutantAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscribeToPollutantAlertsRequest_descriptor,
        new java.lang.String[] { "Location", "Pollutants", });
    internal_static_UnsubscribeFromAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UnsubscribeFromAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnsubscribeFromAlertsRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_Pollutant_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Pollutant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pollutant_descriptor,
        new java.lang.String[] { "Name", "Level", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
