// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlertService.proto

package smart.air.pollution.alert;

public interface SubscribeToPollutantAlertsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscribeToPollutantAlertsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  java.util.List<smart.air.pollution.alert.Pollutant> 
      getPollutantsList();
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  smart.air.pollution.alert.Pollutant getPollutants(int index);
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  int getPollutantsCount();
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  java.util.List<? extends smart.air.pollution.alert.PollutantOrBuilder> 
      getPollutantsOrBuilderList();
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  smart.air.pollution.alert.PollutantOrBuilder getPollutantsOrBuilder(
      int index);
}
