// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlertService.proto

package smart.air.pollution.alert;

/**
 * Protobuf type {@code SubscribeToPollutantAlertsRequest}
 */
public  final class SubscribeToPollutantAlertsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubscribeToPollutantAlertsRequest)
    SubscribeToPollutantAlertsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeToPollutantAlertsRequest.newBuilder() to construct.
  private SubscribeToPollutantAlertsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeToPollutantAlertsRequest() {
    location_ = "";
    pollutants_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubscribeToPollutantAlertsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            location_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              pollutants_ = new java.util.ArrayList<smart.air.pollution.alert.Pollutant>();
              mutable_bitField0_ |= 0x00000002;
            }
            pollutants_.add(
                input.readMessage(smart.air.pollution.alert.Pollutant.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        pollutants_ = java.util.Collections.unmodifiableList(pollutants_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smart.air.pollution.alert.AlertServiceImpl.internal_static_SubscribeToPollutantAlertsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smart.air.pollution.alert.AlertServiceImpl.internal_static_SubscribeToPollutantAlertsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.class, smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int LOCATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object location_;
  /**
   * <code>string location = 1;</code>
   */
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location_ = s;
      return s;
    }
  }
  /**
   * <code>string location = 1;</code>
   */
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POLLUTANTS_FIELD_NUMBER = 2;
  private java.util.List<smart.air.pollution.alert.Pollutant> pollutants_;
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  public java.util.List<smart.air.pollution.alert.Pollutant> getPollutantsList() {
    return pollutants_;
  }
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  public java.util.List<? extends smart.air.pollution.alert.PollutantOrBuilder> 
      getPollutantsOrBuilderList() {
    return pollutants_;
  }
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  public int getPollutantsCount() {
    return pollutants_.size();
  }
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  public smart.air.pollution.alert.Pollutant getPollutants(int index) {
    return pollutants_.get(index);
  }
  /**
   * <code>repeated .Pollutant pollutants = 2;</code>
   */
  public smart.air.pollution.alert.PollutantOrBuilder getPollutantsOrBuilder(
      int index) {
    return pollutants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getLocationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, location_);
    }
    for (int i = 0; i < pollutants_.size(); i++) {
      output.writeMessage(2, pollutants_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getLocationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, location_);
    }
    for (int i = 0; i < pollutants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, pollutants_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smart.air.pollution.alert.SubscribeToPollutantAlertsRequest)) {
      return super.equals(obj);
    }
    smart.air.pollution.alert.SubscribeToPollutantAlertsRequest other = (smart.air.pollution.alert.SubscribeToPollutantAlertsRequest) obj;

    boolean result = true;
    result = result && getLocation()
        .equals(other.getLocation());
    result = result && getPollutantsList()
        .equals(other.getPollutantsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation().hashCode();
    if (getPollutantsCount() > 0) {
      hash = (37 * hash) + POLLUTANTS_FIELD_NUMBER;
      hash = (53 * hash) + getPollutantsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smart.air.pollution.alert.SubscribeToPollutantAlertsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubscribeToPollutantAlertsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubscribeToPollutantAlertsRequest)
      smart.air.pollution.alert.SubscribeToPollutantAlertsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smart.air.pollution.alert.AlertServiceImpl.internal_static_SubscribeToPollutantAlertsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smart.air.pollution.alert.AlertServiceImpl.internal_static_SubscribeToPollutantAlertsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.class, smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.Builder.class);
    }

    // Construct using smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPollutantsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      location_ = "";

      if (pollutantsBuilder_ == null) {
        pollutants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        pollutantsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smart.air.pollution.alert.AlertServiceImpl.internal_static_SubscribeToPollutantAlertsRequest_descriptor;
    }

    @java.lang.Override
    public smart.air.pollution.alert.SubscribeToPollutantAlertsRequest getDefaultInstanceForType() {
      return smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public smart.air.pollution.alert.SubscribeToPollutantAlertsRequest build() {
      smart.air.pollution.alert.SubscribeToPollutantAlertsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smart.air.pollution.alert.SubscribeToPollutantAlertsRequest buildPartial() {
      smart.air.pollution.alert.SubscribeToPollutantAlertsRequest result = new smart.air.pollution.alert.SubscribeToPollutantAlertsRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.location_ = location_;
      if (pollutantsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          pollutants_ = java.util.Collections.unmodifiableList(pollutants_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.pollutants_ = pollutants_;
      } else {
        result.pollutants_ = pollutantsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smart.air.pollution.alert.SubscribeToPollutantAlertsRequest) {
        return mergeFrom((smart.air.pollution.alert.SubscribeToPollutantAlertsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smart.air.pollution.alert.SubscribeToPollutantAlertsRequest other) {
      if (other == smart.air.pollution.alert.SubscribeToPollutantAlertsRequest.getDefaultInstance()) return this;
      if (!other.getLocation().isEmpty()) {
        location_ = other.location_;
        onChanged();
      }
      if (pollutantsBuilder_ == null) {
        if (!other.pollutants_.isEmpty()) {
          if (pollutants_.isEmpty()) {
            pollutants_ = other.pollutants_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePollutantsIsMutable();
            pollutants_.addAll(other.pollutants_);
          }
          onChanged();
        }
      } else {
        if (!other.pollutants_.isEmpty()) {
          if (pollutantsBuilder_.isEmpty()) {
            pollutantsBuilder_.dispose();
            pollutantsBuilder_ = null;
            pollutants_ = other.pollutants_;
            bitField0_ = (bitField0_ & ~0x00000002);
            pollutantsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPollutantsFieldBuilder() : null;
          } else {
            pollutantsBuilder_.addAllMessages(other.pollutants_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smart.air.pollution.alert.SubscribeToPollutantAlertsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smart.air.pollution.alert.SubscribeToPollutantAlertsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object location_ = "";
    /**
     * <code>string location = 1;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string location = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string location = 1;</code>
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string location = 1;</code>
     */
    public Builder clearLocation() {
      
      location_ = getDefaultInstance().getLocation();
      onChanged();
      return this;
    }
    /**
     * <code>string location = 1;</code>
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location_ = value;
      onChanged();
      return this;
    }

    private java.util.List<smart.air.pollution.alert.Pollutant> pollutants_ =
      java.util.Collections.emptyList();
    private void ensurePollutantsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        pollutants_ = new java.util.ArrayList<smart.air.pollution.alert.Pollutant>(pollutants_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        smart.air.pollution.alert.Pollutant, smart.air.pollution.alert.Pollutant.Builder, smart.air.pollution.alert.PollutantOrBuilder> pollutantsBuilder_;

    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public java.util.List<smart.air.pollution.alert.Pollutant> getPollutantsList() {
      if (pollutantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pollutants_);
      } else {
        return pollutantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public int getPollutantsCount() {
      if (pollutantsBuilder_ == null) {
        return pollutants_.size();
      } else {
        return pollutantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public smart.air.pollution.alert.Pollutant getPollutants(int index) {
      if (pollutantsBuilder_ == null) {
        return pollutants_.get(index);
      } else {
        return pollutantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder setPollutants(
        int index, smart.air.pollution.alert.Pollutant value) {
      if (pollutantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePollutantsIsMutable();
        pollutants_.set(index, value);
        onChanged();
      } else {
        pollutantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder setPollutants(
        int index, smart.air.pollution.alert.Pollutant.Builder builderForValue) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.set(index, builderForValue.build());
        onChanged();
      } else {
        pollutantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder addPollutants(smart.air.pollution.alert.Pollutant value) {
      if (pollutantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePollutantsIsMutable();
        pollutants_.add(value);
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder addPollutants(
        int index, smart.air.pollution.alert.Pollutant value) {
      if (pollutantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePollutantsIsMutable();
        pollutants_.add(index, value);
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder addPollutants(
        smart.air.pollution.alert.Pollutant.Builder builderForValue) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.add(builderForValue.build());
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder addPollutants(
        int index, smart.air.pollution.alert.Pollutant.Builder builderForValue) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.add(index, builderForValue.build());
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder addAllPollutants(
        java.lang.Iterable<? extends smart.air.pollution.alert.Pollutant> values) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pollutants_);
        onChanged();
      } else {
        pollutantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder clearPollutants() {
      if (pollutantsBuilder_ == null) {
        pollutants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        pollutantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public Builder removePollutants(int index) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.remove(index);
        onChanged();
      } else {
        pollutantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public smart.air.pollution.alert.Pollutant.Builder getPollutantsBuilder(
        int index) {
      return getPollutantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public smart.air.pollution.alert.PollutantOrBuilder getPollutantsOrBuilder(
        int index) {
      if (pollutantsBuilder_ == null) {
        return pollutants_.get(index);  } else {
        return pollutantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public java.util.List<? extends smart.air.pollution.alert.PollutantOrBuilder> 
         getPollutantsOrBuilderList() {
      if (pollutantsBuilder_ != null) {
        return pollutantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pollutants_);
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public smart.air.pollution.alert.Pollutant.Builder addPollutantsBuilder() {
      return getPollutantsFieldBuilder().addBuilder(
          smart.air.pollution.alert.Pollutant.getDefaultInstance());
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public smart.air.pollution.alert.Pollutant.Builder addPollutantsBuilder(
        int index) {
      return getPollutantsFieldBuilder().addBuilder(
          index, smart.air.pollution.alert.Pollutant.getDefaultInstance());
    }
    /**
     * <code>repeated .Pollutant pollutants = 2;</code>
     */
    public java.util.List<smart.air.pollution.alert.Pollutant.Builder> 
         getPollutantsBuilderList() {
      return getPollutantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        smart.air.pollution.alert.Pollutant, smart.air.pollution.alert.Pollutant.Builder, smart.air.pollution.alert.PollutantOrBuilder> 
        getPollutantsFieldBuilder() {
      if (pollutantsBuilder_ == null) {
        pollutantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            smart.air.pollution.alert.Pollutant, smart.air.pollution.alert.Pollutant.Builder, smart.air.pollution.alert.PollutantOrBuilder>(
                pollutants_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        pollutants_ = null;
      }
      return pollutantsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubscribeToPollutantAlertsRequest)
  }

  // @@protoc_insertion_point(class_scope:SubscribeToPollutantAlertsRequest)
  private static final smart.air.pollution.alert.SubscribeToPollutantAlertsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smart.air.pollution.alert.SubscribeToPollutantAlertsRequest();
  }

  public static smart.air.pollution.alert.SubscribeToPollutantAlertsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeToPollutantAlertsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeToPollutantAlertsRequest>() {
    @java.lang.Override
    public SubscribeToPollutantAlertsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubscribeToPollutantAlertsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubscribeToPollutantAlertsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribeToPollutantAlertsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smart.air.pollution.alert.SubscribeToPollutantAlertsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

