// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataService.proto

package smart.air.pollution.historicaldata;

public interface GetHistoricalDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetHistoricalDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   */
  long getEndTime();
}
