// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataService.proto

package smart.air.pollution.historicaldata;

public interface GetHistoricalDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetHistoricalDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 TimeStamp = 1;</code>
   */
  long getTimeStamp();

  /**
   * <code>int32 AQI = 2;</code>
   */
  int getAQI();

  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  java.util.List<smart.air.pollution.historicaldata.Pollutant> 
      getPollutantsList();
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  smart.air.pollution.historicaldata.Pollutant getPollutants(int index);
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  int getPollutantsCount();
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  java.util.List<? extends smart.air.pollution.historicaldata.PollutantOrBuilder> 
      getPollutantsOrBuilderList();
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  smart.air.pollution.historicaldata.PollutantOrBuilder getPollutantsOrBuilder(
      int index);
}
