// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataService.proto

package smart.air.pollution.historicaldata;

/**
 * Protobuf type {@code GetHistoricalDataResponse}
 */
public  final class GetHistoricalDataResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetHistoricalDataResponse)
    GetHistoricalDataResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetHistoricalDataResponse.newBuilder() to construct.
  private GetHistoricalDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetHistoricalDataResponse() {
    timeStamp_ = 0L;
    aQI_ = 0;
    pollutants_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetHistoricalDataResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timeStamp_ = input.readInt64();
            break;
          }
          case 16: {

            aQI_ = input.readInt32();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              pollutants_ = new java.util.ArrayList<smart.air.pollution.historicaldata.Pollutant>();
              mutable_bitField0_ |= 0x00000004;
            }
            pollutants_.add(
                input.readMessage(smart.air.pollution.historicaldata.Pollutant.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        pollutants_ = java.util.Collections.unmodifiableList(pollutants_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return smart.air.pollution.historicaldata.HistoricalDataServiceimpl.internal_static_GetHistoricalDataResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return smart.air.pollution.historicaldata.HistoricalDataServiceimpl.internal_static_GetHistoricalDataResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            smart.air.pollution.historicaldata.GetHistoricalDataResponse.class, smart.air.pollution.historicaldata.GetHistoricalDataResponse.Builder.class);
  }

  private int bitField0_;
  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timeStamp_;
  /**
   * <code>int64 TimeStamp = 1;</code>
   */
  public long getTimeStamp() {
    return timeStamp_;
  }

  public static final int AQI_FIELD_NUMBER = 2;
  private int aQI_;
  /**
   * <code>int32 AQI = 2;</code>
   */
  public int getAQI() {
    return aQI_;
  }

  public static final int POLLUTANTS_FIELD_NUMBER = 3;
  private java.util.List<smart.air.pollution.historicaldata.Pollutant> pollutants_;
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  public java.util.List<smart.air.pollution.historicaldata.Pollutant> getPollutantsList() {
    return pollutants_;
  }
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  public java.util.List<? extends smart.air.pollution.historicaldata.PollutantOrBuilder> 
      getPollutantsOrBuilderList() {
    return pollutants_;
  }
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  public int getPollutantsCount() {
    return pollutants_.size();
  }
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  public smart.air.pollution.historicaldata.Pollutant getPollutants(int index) {
    return pollutants_.get(index);
  }
  /**
   * <code>repeated .Pollutant pollutants = 3;</code>
   */
  public smart.air.pollution.historicaldata.PollutantOrBuilder getPollutantsOrBuilder(
      int index) {
    return pollutants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timeStamp_ != 0L) {
      output.writeInt64(1, timeStamp_);
    }
    if (aQI_ != 0) {
      output.writeInt32(2, aQI_);
    }
    for (int i = 0; i < pollutants_.size(); i++) {
      output.writeMessage(3, pollutants_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timeStamp_);
    }
    if (aQI_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, aQI_);
    }
    for (int i = 0; i < pollutants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, pollutants_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof smart.air.pollution.historicaldata.GetHistoricalDataResponse)) {
      return super.equals(obj);
    }
    smart.air.pollution.historicaldata.GetHistoricalDataResponse other = (smart.air.pollution.historicaldata.GetHistoricalDataResponse) obj;

    boolean result = true;
    result = result && (getTimeStamp()
        == other.getTimeStamp());
    result = result && (getAQI()
        == other.getAQI());
    result = result && getPollutantsList()
        .equals(other.getPollutantsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (37 * hash) + AQI_FIELD_NUMBER;
    hash = (53 * hash) + getAQI();
    if (getPollutantsCount() > 0) {
      hash = (37 * hash) + POLLUTANTS_FIELD_NUMBER;
      hash = (53 * hash) + getPollutantsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(smart.air.pollution.historicaldata.GetHistoricalDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetHistoricalDataResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetHistoricalDataResponse)
      smart.air.pollution.historicaldata.GetHistoricalDataResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smart.air.pollution.historicaldata.HistoricalDataServiceimpl.internal_static_GetHistoricalDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smart.air.pollution.historicaldata.HistoricalDataServiceimpl.internal_static_GetHistoricalDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smart.air.pollution.historicaldata.GetHistoricalDataResponse.class, smart.air.pollution.historicaldata.GetHistoricalDataResponse.Builder.class);
    }

    // Construct using smart.air.pollution.historicaldata.GetHistoricalDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPollutantsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timeStamp_ = 0L;

      aQI_ = 0;

      if (pollutantsBuilder_ == null) {
        pollutants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        pollutantsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return smart.air.pollution.historicaldata.HistoricalDataServiceimpl.internal_static_GetHistoricalDataResponse_descriptor;
    }

    @java.lang.Override
    public smart.air.pollution.historicaldata.GetHistoricalDataResponse getDefaultInstanceForType() {
      return smart.air.pollution.historicaldata.GetHistoricalDataResponse.getDefaultInstance();
    }

    @java.lang.Override
    public smart.air.pollution.historicaldata.GetHistoricalDataResponse build() {
      smart.air.pollution.historicaldata.GetHistoricalDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public smart.air.pollution.historicaldata.GetHistoricalDataResponse buildPartial() {
      smart.air.pollution.historicaldata.GetHistoricalDataResponse result = new smart.air.pollution.historicaldata.GetHistoricalDataResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.timeStamp_ = timeStamp_;
      result.aQI_ = aQI_;
      if (pollutantsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          pollutants_ = java.util.Collections.unmodifiableList(pollutants_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.pollutants_ = pollutants_;
      } else {
        result.pollutants_ = pollutantsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof smart.air.pollution.historicaldata.GetHistoricalDataResponse) {
        return mergeFrom((smart.air.pollution.historicaldata.GetHistoricalDataResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(smart.air.pollution.historicaldata.GetHistoricalDataResponse other) {
      if (other == smart.air.pollution.historicaldata.GetHistoricalDataResponse.getDefaultInstance()) return this;
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      if (other.getAQI() != 0) {
        setAQI(other.getAQI());
      }
      if (pollutantsBuilder_ == null) {
        if (!other.pollutants_.isEmpty()) {
          if (pollutants_.isEmpty()) {
            pollutants_ = other.pollutants_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePollutantsIsMutable();
            pollutants_.addAll(other.pollutants_);
          }
          onChanged();
        }
      } else {
        if (!other.pollutants_.isEmpty()) {
          if (pollutantsBuilder_.isEmpty()) {
            pollutantsBuilder_.dispose();
            pollutantsBuilder_ = null;
            pollutants_ = other.pollutants_;
            bitField0_ = (bitField0_ & ~0x00000004);
            pollutantsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPollutantsFieldBuilder() : null;
          } else {
            pollutantsBuilder_.addAllMessages(other.pollutants_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      smart.air.pollution.historicaldata.GetHistoricalDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (smart.air.pollution.historicaldata.GetHistoricalDataResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long timeStamp_ ;
    /**
     * <code>int64 TimeStamp = 1;</code>
     */
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>int64 TimeStamp = 1;</code>
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 TimeStamp = 1;</code>
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    private int aQI_ ;
    /**
     * <code>int32 AQI = 2;</code>
     */
    public int getAQI() {
      return aQI_;
    }
    /**
     * <code>int32 AQI = 2;</code>
     */
    public Builder setAQI(int value) {
      
      aQI_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 AQI = 2;</code>
     */
    public Builder clearAQI() {
      
      aQI_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<smart.air.pollution.historicaldata.Pollutant> pollutants_ =
      java.util.Collections.emptyList();
    private void ensurePollutantsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        pollutants_ = new java.util.ArrayList<smart.air.pollution.historicaldata.Pollutant>(pollutants_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        smart.air.pollution.historicaldata.Pollutant, smart.air.pollution.historicaldata.Pollutant.Builder, smart.air.pollution.historicaldata.PollutantOrBuilder> pollutantsBuilder_;

    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public java.util.List<smart.air.pollution.historicaldata.Pollutant> getPollutantsList() {
      if (pollutantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pollutants_);
      } else {
        return pollutantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public int getPollutantsCount() {
      if (pollutantsBuilder_ == null) {
        return pollutants_.size();
      } else {
        return pollutantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public smart.air.pollution.historicaldata.Pollutant getPollutants(int index) {
      if (pollutantsBuilder_ == null) {
        return pollutants_.get(index);
      } else {
        return pollutantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder setPollutants(
        int index, smart.air.pollution.historicaldata.Pollutant value) {
      if (pollutantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePollutantsIsMutable();
        pollutants_.set(index, value);
        onChanged();
      } else {
        pollutantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder setPollutants(
        int index, smart.air.pollution.historicaldata.Pollutant.Builder builderForValue) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.set(index, builderForValue.build());
        onChanged();
      } else {
        pollutantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder addPollutants(smart.air.pollution.historicaldata.Pollutant value) {
      if (pollutantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePollutantsIsMutable();
        pollutants_.add(value);
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder addPollutants(
        int index, smart.air.pollution.historicaldata.Pollutant value) {
      if (pollutantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePollutantsIsMutable();
        pollutants_.add(index, value);
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder addPollutants(
        smart.air.pollution.historicaldata.Pollutant.Builder builderForValue) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.add(builderForValue.build());
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder addPollutants(
        int index, smart.air.pollution.historicaldata.Pollutant.Builder builderForValue) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.add(index, builderForValue.build());
        onChanged();
      } else {
        pollutantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder addAllPollutants(
        java.lang.Iterable<? extends smart.air.pollution.historicaldata.Pollutant> values) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pollutants_);
        onChanged();
      } else {
        pollutantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder clearPollutants() {
      if (pollutantsBuilder_ == null) {
        pollutants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        pollutantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public Builder removePollutants(int index) {
      if (pollutantsBuilder_ == null) {
        ensurePollutantsIsMutable();
        pollutants_.remove(index);
        onChanged();
      } else {
        pollutantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public smart.air.pollution.historicaldata.Pollutant.Builder getPollutantsBuilder(
        int index) {
      return getPollutantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public smart.air.pollution.historicaldata.PollutantOrBuilder getPollutantsOrBuilder(
        int index) {
      if (pollutantsBuilder_ == null) {
        return pollutants_.get(index);  } else {
        return pollutantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public java.util.List<? extends smart.air.pollution.historicaldata.PollutantOrBuilder> 
         getPollutantsOrBuilderList() {
      if (pollutantsBuilder_ != null) {
        return pollutantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pollutants_);
      }
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public smart.air.pollution.historicaldata.Pollutant.Builder addPollutantsBuilder() {
      return getPollutantsFieldBuilder().addBuilder(
          smart.air.pollution.historicaldata.Pollutant.getDefaultInstance());
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public smart.air.pollution.historicaldata.Pollutant.Builder addPollutantsBuilder(
        int index) {
      return getPollutantsFieldBuilder().addBuilder(
          index, smart.air.pollution.historicaldata.Pollutant.getDefaultInstance());
    }
    /**
     * <code>repeated .Pollutant pollutants = 3;</code>
     */
    public java.util.List<smart.air.pollution.historicaldata.Pollutant.Builder> 
         getPollutantsBuilderList() {
      return getPollutantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        smart.air.pollution.historicaldata.Pollutant, smart.air.pollution.historicaldata.Pollutant.Builder, smart.air.pollution.historicaldata.PollutantOrBuilder> 
        getPollutantsFieldBuilder() {
      if (pollutantsBuilder_ == null) {
        pollutantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            smart.air.pollution.historicaldata.Pollutant, smart.air.pollution.historicaldata.Pollutant.Builder, smart.air.pollution.historicaldata.PollutantOrBuilder>(
                pollutants_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        pollutants_ = null;
      }
      return pollutantsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetHistoricalDataResponse)
  }

  // @@protoc_insertion_point(class_scope:GetHistoricalDataResponse)
  private static final smart.air.pollution.historicaldata.GetHistoricalDataResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new smart.air.pollution.historicaldata.GetHistoricalDataResponse();
  }

  public static smart.air.pollution.historicaldata.GetHistoricalDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetHistoricalDataResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetHistoricalDataResponse>() {
    @java.lang.Override
    public GetHistoricalDataResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetHistoricalDataResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetHistoricalDataResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetHistoricalDataResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public smart.air.pollution.historicaldata.GetHistoricalDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

