// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HistoricalDataService.proto

package smart.air.pollution.historicaldata;

public final class HistoricalDataServiceimpl {
  private HistoricalDataServiceimpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetHistoricalDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetHistoricalDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetHistoricalDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetHistoricalDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Pollutant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Pollutant_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033HistoricalDataService.proto\"R\n\030GetHist" +
      "oricalDataRequest\022\020\n\010location\030\001 \001(\t\022\022\n\ns" +
      "tart_time\030\002 \001(\003\022\020\n\010end_time\030\003 \001(\003\"[\n\031Get" +
      "HistoricalDataResponse\022\021\n\tTimeStamp\030\001 \001(" +
      "\003\022\013\n\003AQI\030\002 \001(\005\022\036\n\npollutants\030\003 \003(\0132\n.Pol" +
      "lutant\"(\n\tPollutant\022\014\n\004name\030\001 \001(\t\022\r\n\005lev" +
      "el\030\002 \001(\0022i\n\025HistoricalDataService\022P\n\021Get" +
      "HistoricalData\022\031.GetHistoricalDataReques" +
      "t\032\032.GetHistoricalDataResponse\"\000(\0010\001BA\n\"s" +
      "mart.air.pollution.historicaldataB\031Histo" +
      "ricalDataServiceimplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GetHistoricalDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetHistoricalDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetHistoricalDataRequest_descriptor,
        new java.lang.String[] { "Location", "StartTime", "EndTime", });
    internal_static_GetHistoricalDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetHistoricalDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetHistoricalDataResponse_descriptor,
        new java.lang.String[] { "TimeStamp", "AQI", "Pollutants", });
    internal_static_Pollutant_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Pollutant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Pollutant_descriptor,
        new java.lang.String[] { "Name", "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
